---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install a list of packages on centos
      yum:
        name:
          - vim 
          - tree 
          - telnet 
        state=present
      when: ansible_distribution == "CentOS7"
    - name: Install a list of packages on debian and ubuntu
      apt:
        name:
          - tree 
          - vim 
          - telnet 
        state=present
      when: ansible_distribution == "Ubuntu" "Debian8"