---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: /tmp/wordpress-5.1.1.tar
        dest: /tmp
        remote_src: yes