---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: Install and start apache webserver on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: httpd
        state: present 
    - name: Start apache web server
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install and start apache webserver on Debian
      when: ansible_distribution == 'Debian'
      apt:
        name: apache2
        state: present 
    - name: Start apache web server
      service:
        name: apache2
        state: started
        enabled: yes
    
    - name: Install and start apache webserver on Ubuntu
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: apache2
        state: present 
    - name: Start apache web server
      service:
        name: apache2
        state: started
        enabled: yes
