---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: Install and start apache webserver on CentOS
      when: ansible_distribution == 'CentOS'
      yum:
        name: httpd
        state: present 
    - name: Start apache web server
      service:
        name: httpd
        state: started
        enabled: yes
